### ISSUE TITLE
[Linux] Building meshlab fails (nexus and libE57Format errors when compiling)

### ISSUE THREAD

**Issue by Nalonoid** [cnr-isti-vclab/meshlab#1447]
Hello,

I am currently trying to build meshlab from the main branch, but compiling throws errors.

My system information:

kubuntu 23.10 x86_64 
kernel 6.5.0-13-generic 
qt 5.15.10
qt creator 10.0.2
gcc 13.2.0
cmake 3.27.4

```
external/downloads/libE57Format-2.3.0/include/E57Format.h
external/downloads/nexus-master/src/corto/src/tunstall.cpp
```

It is mainly undefined types such as:

```
‘int16_t’ has not been declared in ‘std’
‘uint32_t’ does not name a type
‘uint32_t’ has not been declared
Unknown type name 'uint32_t'
```
And so on...

What I did:

```
git clone --recursive https://github.com/cnr-isti-vclab/meshlab
mkdir meshlab/build && cd meshlab/build
cmake ..
make -j$(nproc)
````
Fails with the same errors as when opening meshlab with qtcreator.
Same result when using the scripts to build meshlab (`0_setup_env.sh` then `1_build.sh`)
By the way, in the script `0_setup_env.sh` the package `qt5-default` has no candidate for ubuntu based distros > 22.04. It should be replaced with `qtbase5-dev` and `qt5-qmake`.

Am I the only one with this build problem? :-(

Cheers

**Comment by alemuntoni** [comment]
I don't experience these kind of errors... The only difference between your configuration and mine is the GCC version, therefore I think that some additional #include is required in that version. Maybe updating the external libraries should fix this issue, but it is something that I'll work on when Ubuntu 24.04 will be released.

**Comment by An-u-rag** [comment]
I think I have the same problem as @Nalonoid. I get a bunch of "error: ‘uint32_t’ has not been declared in ‘std’" kind of errors in libE57Format-2.3.0/include header files. 

My system information:
ubuntu 20.04 x86_64
qt 5.15.3
qt creator 6.0.2
gcc 10.5.0
cmake 3.29.0-rc1

I experience quite a few internal compiler errors and segmentation faults while running the make command as well.

**Comment by axhan** [comment]
sed -i '1 i\#include <cstdint>' src/external/downloads/{nexus-master/src/corto/include/corto/tunstall.h,libE57Format-2.3.0/include/E57Format.h}

run from the meshlab source dir makes the E57 errors go away. Fix shamelessly stolen from the Arch AUR PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=meshlab

**Comment by alemuntoni** [comment]
This issue should be solved in the devel branch (that will be merged in the next meshlab version).
Although nexus should be solved (just remove the folder from src/external/downloads if it still persists), for libe57  an update is needed, and I did it in the devel branch. Therefore, right now the main branch cannot be compiled with a recent gcc version.

**Comment by axhan** [comment]
The E57 related compilation errors I had to fix with the sed hack above were with the devel branch of meshlab (downloaded yesterday) + clang 18.

**Comment by alemuntoni** [comment]
That's weird. The devel branch should download libE57Format-3.1.1 (see [here](https://github.com/cnr-isti-vclab/meshlab/blob/bab066ee6b8b3cf601c665e3b281fd72abf27795/src/external/e57.cmake#L7)).

**Comment by axhan** [comment]
And so it does. Sure as I was that cloning using the git URL as copied under "Code" on GitHub would get the "devel" branch selected in the popup in the same row, I was wrong and on the "main" branch unwittingly.

I apologize for my confusion.

**Comment by alemuntoni** [comment]
@axhan no problem :) happy that it builds as expected!

**Comment by axhan** [comment]
After deselecting E57_RELEASE_LTO it compiles with no linker error.
